CREATE TABLE APPLICATION_USER(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ENABLED BOOLEAN DEFAULT FALSE	
);

CREATE TABLE APPLICATION_ROLE(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) DEFAULT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL
);

CREATE TABLE USER_ROLE(
	ID BIGINT(20) NOT NULL PRIMARY KEY,
	USER_ID BIGINT(20) NOT NULL,
	ROLE_ID BIGINT(20) NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES APPLICATION_USER (ID),
	FOREIGN KEY (ROLE_ID) REFERENCES APPLICATION_ROLE (ID)
);