CREATE TABLE USER (
	ID BIGINT NOT NULL PRIMARY KEY,
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	EMAIL VARCHAR(255),
	ENABLED BOOLEAN DEFAULT FALSE
);

CREATE TABLE ROLE (
	ID BIGINT NOT NULL PRIMARY KEY,
	NAME VARCHAR(255)
);

CREATE TABLE USERS_ROLES (
	USER_ID BIGINT NOT NULL,
	ROLE_ID BIGINT NOT NULL,
	CONSTRAINT USERS_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID),
	CONSTRAINT USERS_ROLES_USER_FK FOREIGN KEY (USER_ID) REFERENCES USER(ID),
	CONSTRAINT USERS_ROLES_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE PRIVILEGE (
	ID BIGINT NOT NULL PRIMARY KEY,
	NAME VARCHAR(255)
);

CREATE TABLE ROLES_PRIVILEGES (
	ROLE_ID BIGINT NOT NULL,
	PRIVILEGE_ID BIGINT NOT NULL,
	CONSTRAINT ROLES_PRIVILEGES_PK PRIMARY KEY (ROLE_ID, PRIVILEGE_ID),
	CONSTRAINT ROLES_PRIVILEGES_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
	CONSTRAINT ROLES_PRIVILEGES_PRIVILEGE_FK FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE(ID)
);